

  0%|          | 0/200 [00:46<?, ?it/s]
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ff6ba2fda60>
Traceback (most recent call last):
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
    self._shutdown_workers()
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1430, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 936, in wait
    ready = selector.select(timeout)
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
Exception in thread Exception in thread Exception in thread Exception in thread QueueFeederThreadQueueFeederThreadQueueFeederThreadQueueFeederThread:
Traceback (most recent call last):
:
:
:
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/queues.py", line 239, in _feed
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/queues.py", line 239, in _feed
      File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/queues.py", line 239, in _feed
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/queues.py", line 239, in _feed
reader_close()
    reader_close()reader_close()  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 182, in close
reader_close()
      File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 182, in close
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 182, in close
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 182, in close
self._close()
self._close()self._close()self._close()  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 366, in _close
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 366, in _close
      File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 366, in _close
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)        _close(self._handle)
_close(self._handle)_close(self._handle)
OSError
OSError: OSErrorOSError: [Errno 9] Bad file descriptor: : [Errno 9] Bad file descriptor
[Errno 9] Bad file descriptor[Errno 9] Bad file descriptor
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/threading.py", line 980, in _bootstrap_inner
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/threading.py", line 980, in _bootstrap_inner
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/threading.py", line 980, in _bootstrap_inner
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/threading.py", line 980, in _bootstrap_inner
                self.run()self.run()self.run()self.run()
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/threading.py", line 917, in run
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/threading.py", line 917, in run
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/threading.py", line 917, in run
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/threading.py", line 917, in run
                self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/queues.py", line 271, in _feed
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/queues.py", line 271, in _feed
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/queues.py", line 271, in _feed
  File "/home/johann/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/queues.py", line 271, in _feed
            queue_sem.release()    queue_sem.release()queue_sem.release()
queue_sem.release()
ValueError
ValueErrorValueError: ValueError: : semaphore or lock released too many times: semaphore or lock released too many timessemaphore or lock released too many times
semaphore or lock released too many times
(30758, 14)
(74811, 14)
(70579, 14)
(96989, 14)
(92799, 14)
(55644, 14)
(133273, 14)
(94895, 14)
(142492, 14)
(121595, 14)
(6912, 14)
(12088, 14)
(6955, 14)
(16258, 14)
(11063, 14)
(53137, 14)
(54815, 14)
(57226, 14)
(40308, 14)
(86515, 14)
(47113, 14)
(107777, 14)
(89350, 14)
(109161, 14)
(87680, 14)
(16052, 14)
(32144, 14)
(15369, 14)
(25245, 14)
(10213, 14)
(54788, 14)
(120244, 14)
(107238, 14)
(128525, 14)
(81716, 14)
(97101, 14)
(158952, 14)
(177062, 14)
(135643, 14)
(139051, 14)
(5501, 14)
(3202, 14)
(2850, 14)
(3073, 14)
(3370, 14)
(7354, 14)
(3440, 14)
(1975, 14)
(3065, 14)
(8603, 14)
(32051, 14)
(80987, 14)
(72985, 14)
(75559, 14)
(39369, 14)
(67701, 14)
(171621, 14)
(54411, 14)
(153431, 14)
(87968, 14)
(4955, 14)
(9642, 14)
(8864, 14)
(7841, 14)
(10175, 14)
(39320, 14)
(134934, 14)
(68140, 14)
(165695, 14)
(69354, 14)
(22444, 14)
(13089, 14)
(9376, 14)
(15687, 14)
(22924, 14)
(4964, 14)
(2500, 14)
(1688, 14)
(1924, 14)
(4924, 14)
(19580, 14)
(23525, 14)
(23000, 14)
(20078, 14)
(26085, 14)
(17003, 14)
(14525, 14)
(23152, 14)
(11950, 14)
(27435, 14)
(8037, 14)
(4556, 14)
(5036, 14)
(2508, 14)
(9609, 14)
(1515, 14)
(2977, 14)
(2366, 14)
(1510, 14)
(3349, 14)
Shape of df_target: (4695, 14)
Number of animals in df_target: 20
Number of phases in df_target: 5
1010.49797657082
Shape of df_target: (4695, 14)
Number of animals in df_target: 20
Number of phases in df_target: 5
1010.49797657082
(30, 14)
(74, 14)
(70, 14)
(96, 14)
(92, 14)
(55, 14)
(133, 14)
(94, 14)
(142, 14)
(121, 14)
(6, 14)
(12, 14)
(6, 14)
(16, 14)
(11, 14)
(53, 14)
(54, 14)
(57, 14)
(40, 14)
(86, 14)
(47, 14)
(107, 14)
(89, 14)
(109, 14)
(87, 14)
(16, 14)
(32, 14)
(15, 14)
(25, 14)
(10, 14)
(54, 14)
(120, 14)
(107, 14)
(128, 14)
(81, 14)
(97, 14)
(158, 14)
(177, 14)
(135, 14)
(139, 14)
(5, 14)
(3, 14)
(2, 14)
(3, 14)
(3, 14)
(7, 14)
(3, 14)
(1, 14)
(3, 14)
(8, 14)
(32, 14)
(80, 14)
(72, 14)
(75, 14)
(39, 14)
(67, 14)
(171, 14)
(54, 14)
(153, 14)
(87, 14)
(4, 14)
(9, 14)
(8, 14)
(7, 14)
(10, 14)
(39, 14)
(134, 14)
(68, 14)
(165, 14)
(69, 14)
(22, 14)
(13, 14)
(9, 14)
(15, 14)
(22, 14)
(4, 14)
(2, 14)
(1, 14)
(1, 14)
(4, 14)
(19, 14)
(23, 14)
(23, 14)
(20, 14)
(26, 14)
(17, 14)
(14, 14)
(23, 14)
(11, 14)
(27, 14)
(8, 14)
(4, 14)
(5, 14)
(2, 14)
(9, 14)
(1, 14)
(2, 14)
(2, 14)
(1, 14)
(3, 14)
Shape of df_target: (4695, 14)
Number of animals in df_target: 20
Number of phases in df_target: 5
1010.49797657082
(307, 14)
(748, 14)
(705, 14)
(969, 14)
(927, 14)
(556, 14)
(1332, 14)
(948, 14)
(1424, 14)
(1215, 14)
(69, 14)
(120, 14)
(69, 14)
(162, 14)
(110, 14)
(531, 14)
(548, 14)
(572, 14)
(403, 14)
(865, 14)
(471, 14)
(1077, 14)
(893, 14)
(1091, 14)
(876, 14)
(160, 14)
(321, 14)
(153, 14)
(252, 14)
(102, 14)
(547, 14)
(1202, 14)
(1072, 14)
(1285, 14)
(817, 14)
(971, 14)
(1589, 14)
(1770, 14)
(1356, 14)
(1390, 14)
(55, 14)
(32, 14)
(28, 14)
(30, 14)
(33, 14)
(73, 14)
(34, 14)
(19, 14)
(30, 14)
(86, 14)
(320, 14)
(809, 14)
(729, 14)
(755, 14)
(393, 14)
(677, 14)
(1716, 14)
(544, 14)
(1534, 14)
(879, 14)
(49, 14)
(96, 14)
(88, 14)
(78, 14)
(101, 14)
(393, 14)
(1349, 14)
(681, 14)
(1656, 14)
(693, 14)
(224, 14)
(130, 14)
(93, 14)
(156, 14)
(229, 14)
(49, 14)
(25, 14)
(16, 14)
(19, 14)
(49, 14)
(195, 14)
(235, 14)
(230, 14)
(200, 14)
(260, 14)
(170, 14)
(145, 14)
(231, 14)
(119, 14)
(274, 14)
(80, 14)
(45, 14)
(50, 14)
(25, 14)
(96, 14)
(15, 14)
(29, 14)
(23, 14)
(15, 14)
(33, 14)
Shape of df_target: (47395, 14)
Number of animals in df_target: 20
Number of phases in df_target: 5
100.10102331469564
(307, 14)
(748, 14)
(705, 14)
(969, 14)
(927, 14)
(556, 14)
(1332, 14)
(948, 14)
(1424, 14)
(1215, 14)
(69, 14)
(120, 14)
(69, 14)
(162, 14)
(110, 14)
(531, 14)
(548, 14)
(572, 14)
(403, 14)
(865, 14)
(471, 14)
(1077, 14)
(893, 14)
(1091, 14)
(876, 14)
(160, 14)
(321, 14)
(153, 14)
(252, 14)
(102, 14)
(547, 14)
(1202, 14)
(1072, 14)
(1285, 14)
(817, 14)
(971, 14)
(1589, 14)
(1770, 14)
(1356, 14)
(1390, 14)
(55, 14)
(32, 14)
(28, 14)
(30, 14)
(33, 14)
(73, 14)
(34, 14)
(19, 14)
(30, 14)
(86, 14)
(320, 14)
(809, 14)
(729, 14)
(755, 14)
(393, 14)
(677, 14)
(1716, 14)
(544, 14)
(1534, 14)
(879, 14)
(49, 14)
(96, 14)
(88, 14)
(78, 14)
(101, 14)
(393, 14)
(1349, 14)
(681, 14)
(1656, 14)
(693, 14)
(224, 14)
(130, 14)
(93, 14)
(156, 14)
(229, 14)
(49, 14)
(25, 14)
(16, 14)
(19, 14)
(49, 14)
(195, 14)
(235, 14)
(230, 14)
(200, 14)
(260, 14)
(170, 14)
(145, 14)
(231, 14)
(119, 14)
(274, 14)
(80, 14)
(45, 14)
(50, 14)
(25, 14)
(96, 14)
(15, 14)
(29, 14)
(23, 14)
(15, 14)
(33, 14)
Shape of df_target: (47395, 14)
Number of animals in df_target: 20
Number of phases in df_target: 5
100.10102331469564